// aitest/web/src/views/project/quality/GapDiscoveryView.tsx
/** Gap Discovery View — full React port with real API scanner. */
import { useEffect } from 'react'
import { useGapScanner, type TestGap } from '@/hooks/useGapScanner'
import { Search, AlertTriangle, RefreshCw, X } from 'lucide-react'

const severityColors: Record<string, string> = {
  critical: 'bg-red-100 text-red-800 border-red-300',
  high: 'bg-orange-100 text-orange-800 border-orange-300',
  medium: 'bg-yellow-100 text-yellow-800 border-yellow-300',
  low: 'bg-blue-100 text-blue-800 border-blue-300',
}

const typeIcons: Record<string, string> = {
  missing_test: '❌', missing_type: '⚠️', low_coverage: '📉',
  flaky_test: '🔄', untested_component: '🧩',
}

export default function GapDiscoveryView() {
  const {
    gaps, allGaps, scanning, progress, stats,
    selectedType, showDismissed,
    setSelectedType, setShowDismissed,
    scan, dismissGap, dismissAll, convertToTask, archiveGap,
  } = useGapScanner()

  useEffect(() => {
    scan()
  }, []) // auto-scan on mount

  return (
    <div className="p-6 max-w-1200">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-xl font-bold flex items-center gap-2">
          <Search size={20} /> 缺口发现
        </h1>
        <button onClick={scan} disabled={scanning} className="btn-outline text-xs flex items-center gap-1.5">
          <RefreshCw size={13} className={scanning ? 'animate-spin' : ''} /> {scanning ? '扫描中...' : '重新扫描'}
        </button>
      </div>

      {/* Stats */}
      {allGaps.length > 0 && (
        <div className="flex gap-4 mb-4 text-xs text-muted-foreground">
          <span>{stats.total} 个缺口</span>
          <span className="text-red-500 font-semibold">{stats.critical} 严重</span>
          <span className="text-orange-500 font-semibold">{stats.high} 高</span>
        </div>
      )}

      {/* Progress */}
      {scanning && (
        <div className="flex items-center gap-2 text-sm text-muted-foreground mb-4">
          <RefreshCw size={14} className="animate-spin" /> {progress}
        </div>
      )}

      {/* Filters */}
      <div className="flex gap-2 mb-4 flex-wrap">
        <button onClick={() => setSelectedType('all')} className={`filter-chip ${selectedType === 'all' ? 'active' : ''}`}>全部</button>
        <button onClick={() => setSelectedType('missing_test')} className={`filter-chip ${selectedType === 'missing_test' ? 'active' : ''}`}>❌ 缺失测试</button>
        <button onClick={() => setSelectedType('missing_type')} className={`filter-chip ${selectedType === 'missing_type' ? 'active' : ''}`}>⚠️ 缺失类型</button>
        <button onClick={() => setSelectedType('low_coverage')} className={`filter-chip ${selectedType === 'low_coverage' ? 'active' : ''}`}>📉 覆盖不足</button>
        <button onClick={() => setSelectedType('flaky_test')} className={`filter-chip ${selectedType === 'flaky_test' ? 'active' : ''}`}>🔄 不稳定</button>
        <button onClick={() => setSelectedType('untested_component')} className={`filter-chip ${selectedType === 'untested_component' ? 'active' : ''}`}>🧩 未测组件</button>
        <div className="flex-1" />
        <label className="flex items-center gap-1 text-xs cursor-pointer">
          <input type="checkbox" checked={showDismissed} onChange={e => setShowDismissed(e.target.checked)} />
          显示已忽略
        </label>
        <button onClick={dismissAll} className="text-xs text-muted-foreground hover:text-destructive">全部忽略</button>
      </div>

      {/* Gap list */}
      {gaps.length === 0 && !scanning ? (
        <div className="text-center py-16 text-muted-foreground text-sm">
          <AlertTriangle size={48} className="mx-auto mb-4 opacity-20" />
          <p>未发现缺口</p>
          <span className="text-xs">所有模块测试覆盖充足。</span>
        </div>
      ) : (
        <div className="space-y-3">
          {gaps.map(gap => (
            <GapCard key={gap.id} gap={gap} onDismiss={dismissGap} onConvert={convertToTask} onArchive={archiveGap} />
          ))}
        </div>
      )}

      <style>{`
        .filter-chip { padding: 3px 10px; border-radius: 9999px; border: 1px solid var(--border); background: transparent; cursor: pointer; font-size: 11px; color: var(--text-secondary); transition: all .15s; }
        .filter-chip:hover { border-color: var(--primary); color: var(--primary); }
        .filter-chip.active { background: var(--primary); color: var(--primary-foreground); border-color: var(--primary); }
      `}</style>
    </div>
  )
}

function GapCard({ gap, onDismiss, onConvert, onArchive }: {
  gap: TestGap
  onDismiss: (id: string) => void
  onConvert: (id: string) => void
  onArchive: (id: string) => void
}) {
  const sev = severityColors[gap.severity] || ''
  const icon = typeIcons[gap.type] || '📌'

  return (
    <div className="glass-card !rounded-xl p-4">
      <div className="flex items-start justify-between mb-2">
        <div className="flex items-center gap-2 min-w-0">
          <span className="text-lg">{icon}</span>
          <div>
            <div className="font-semibold text-sm">{gap.title}</div>
            <div className="flex items-center gap-2 mt-0.5">
              <span className={`text-[10px] px-1.5 py-0.5 rounded border font-semibold ${sev}`}>{gap.severity.toUpperCase()}</span>
              <span className="text-[11px] text-muted-foreground">{gap.module}</span>
              <span className="text-[11px] text-muted-foreground">⏱ {gap.estimatedEffort}</span>
            </div>
          </div>
        </div>
        <div className="flex gap-1 flex-shrink-0">
          <button onClick={() => onConvert(gap.id)} className="btn-mini" title="创建任务">📋</button>
          <button onClick={() => onDismiss(gap.id)} className="btn-mini" title="忽略">✕</button>
          <button onClick={() => onArchive(gap.id)} className="btn-mini" title="归档">📁</button>
        </div>
      </div>
      <p className="text-xs text-muted-foreground mb-2">{gap.description}</p>
      <div className="text-[11px] text-primary font-medium">💡 {gap.suggestion}</div>
      <style>{`
        .btn-mini { background: none; border: 1px solid var(--border); border-radius: 4px; cursor: pointer; padding: 2px 4px; font-size: 11px; opacity: 0.5; }
        .btn-mini:hover { opacity: 1; background: var(--bg-secondary); }
      `}</style>
    </div>
  )
}

// aitest/web/src/views/GapDiscoveryView.vue
<script setup lang="ts">
import { computed, onMounted } from 'vue'
import { useI18n } from 'vue-i18n'
import { useGapScanner } from '@/composables/useGapScanner'
const { t } = useI18n()
const { gaps, scanning, progress, stats, GAP_TYPES, selectedType, showDismissed, scan, dismissGap, dismissAll, convertToTask } = useGapScanner()
onMounted(scan)
const sevBadge: Record<string, string> = { critical: 'badge-err', high: 'badge-warn', medium: 'badge-info', low: '' }
const typeIcons: Record<string, string> = { missing_test:'❌', missing_type:'⚠️', low_coverage:'📉', flaky_test:'🔄', untested_component:'🧩' }
const filterTabs = computed(() => [{id:'all',label:t('gaps.types.all'),icon:'📋'}, ...GAP_TYPES.map(tp => ({id:tp.id, label:t('gaps.types.'+tp.id), icon:tp.icon}))])
function statCount(typeId: string) { const b = stats.value.byType as Record<string,number>; return b[typeId] || 0 }
</script>

<template>
  <div>
    <div class="flex items-center justify-between mb-5">
      <h2 class="text-base font-semibold">{{ t('gaps.title') }}</h2>
      <div class="flex gap-2">
        <button @click="dismissAll" class="btn-outline text-xs" :disabled="gaps.length === 0">{{ t('gaps.dismiss_all') }}</button>
        <button @click="scan" class="btn-primary text-xs" :disabled="scanning">{{ scanning ? t('gaps.scanning') : t('gaps.rescan') }}</button>
      </div>
    </div>

    <div v-if="!scanning" class="flex gap-1.5 mb-4 flex-wrap">
      <button v-for="t2 in filterTabs" :key="t2.id"
        @click="selectedType = t2.id"
        :class="['px-2.5 py-1 rounded-full text-[11px] cursor-pointer border transition-all font-sans',
          selectedType === t2.id ? 'btn-primary !py-1 !text-[11px]' : 'btn-outline !py-1 !text-[11px]']"
      >{{ t2.icon }} {{ t2.label }}
        <span v-if="t2.id !== 'all'" class="ml-1 opacity-50">{{ statCount(t2.id) }}</span>
      </button>
    </div>

    <div v-if="scanning" class="glass-card p-8 text-center space-y-3">
      <div class="text-2xl animate-pulse">🔍</div>
      <div class="text-sm text-muted-foreground font-mono">{{ progress }}</div>
      <div class="h-1.5 bg-muted rounded-full overflow-hidden max-w-md mx-auto"><div class="h-full rounded-full animate-pulse" style="background:var(--primary-gradient); width:60%" /></div>
    </div>

    <div v-else-if="gaps.length === 0" class="glass-card p-16 text-center text-muted-foreground">
      <div class="text-4xl mb-3">✅</div>
      <div class="font-semibold text-lg">{{ t('gaps.no_gaps') }}</div>
      <div class="text-xs mt-1">{{ t('gaps.no_gaps_desc') }}</div>
    </div>

    <div v-else class="grid grid-cols-2 gap-4 max-lg:grid-cols-1">
      <div v-for="gap in gaps" :key="gap.id" class="glass-card !rounded-xl p-5 group cursor-pointer transition-all duration-200">
        <div class="flex items-start gap-3 mb-3">
          <span class="text-xl">{{ typeIcons[gap.type] || '📌' }}</span>
          <div class="flex-1 min-w-0">
            <div class="flex items-center gap-2 mb-1">
              <span :class="['badge text-[10px] font-bold', sevBadge[gap.severity] || 'badge-info']">{{ t('gaps.severity.'+gap.severity) }}</span>
              <span class="text-[11px] text-muted-foreground font-mono">{{ gap.module }}</span>
            </div>
            <div class="text-[13px] font-semibold truncate">{{ gap.title }}</div>
          </div>
        </div>
        <p class="text-xs text-muted-foreground mb-4 line-clamp-2 leading-relaxed">{{ gap.description }}</p>
        <div class="flex gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
          <button @click.stop="convertToTask(gap.id)" class="btn-primary !text-[11px] !py-1.5 !px-3">{{ t('gaps.create_task') }}</button>
          <button @click.stop="dismissGap(gap.id)" class="btn-outline !text-[11px] !py-1.5 !px-3">{{ t('gaps.dismiss') }}</button>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.line-clamp-2 { display:-webkit-box; -webkit-line-clamp:2; -webkit-box-orient:vertical; overflow:hidden; }
</style>
