// aitest/web/src/views/SettingsView.tsx
/** App Settings — React port. Theme, language, provider, budget. */
import { useSettingsStore } from '../stores/settings'
import { Settings, Palette, Globe, Cpu, DollarSign } from 'lucide-react'
import { useTranslation } from 'react-i18next'

const themes = ['default', 'dusk', 'lime', 'ocean', 'retro', 'neo', 'forest', 'oscura']

export default function SettingsView() {
  const { t, i18n } = useTranslation()
  const app = useSettingsStore(s => s.app)
  const updateApp = useSettingsStore(s => s.updateApp)

  return (
    <div className="p-6 max-w-2xl">
      <h1 className="text-xl font-bold mb-6 flex items-center gap-2"><Settings size={20} /> {t('settings.title')}</h1>

      <div className="space-y-6">
        {/* Appearance */}
        <Section icon={Palette} title="外观">
          <div className="grid grid-cols-4 gap-2">
            {themes.map(name => (
              <button key={name} onClick={() => { updateApp({ theme: name }); localStorage.setItem('tlo-theme-name', name); document.documentElement.setAttribute('data-theme', name) }}
                className={`px-3 py-2 rounded-lg text-xs font-medium border transition-colors ${app.theme === name ? 'border-primary bg-primary/10 text-primary' : 'border-border hover:bg-accent'}`}>
                {name}
              </button>
            ))}
          </div>
          <label className="flex items-center gap-2 mt-3 text-sm cursor-pointer">
            <input type="checkbox" checked={app.darkMode} onChange={e => { updateApp({ darkMode: e.target.checked }); document.documentElement.classList.toggle('dark', e.target.checked); localStorage.setItem('tlo-theme', e.target.checked ? 'dark' : 'light') }} />
            {t('theme.dark')}
          </label>
        </Section>

        {/* Language */}
        <Section icon={Globe} title={t('lang.label')}>
          <div className="flex gap-2">
            {['zh', 'en'].map(l => (
              <button key={l} onClick={() => { i18n.changeLanguage(l); localStorage.setItem('tlo-lang', l) }}
                className={`px-4 py-2 rounded-lg text-sm font-medium border transition-colors ${i18n.language === l ? 'border-primary bg-primary/10 text-primary' : 'border-border hover:bg-accent'}`}>
                {l === 'zh' ? '中文' : 'English'}
              </button>
            ))}
          </div>
        </Section>

        {/* Provider */}
        <Section icon={Cpu} title={t('settings.provider')}>
          <select value={app.provider} onChange={e => updateApp({ provider: e.target.value })}
            className="w-full px-3 py-2 border border-border rounded-lg bg-background text-sm">
            {['claude', 'deepseek', 'openai', 'ollama'].map(p => <option key={p} value={p}>{p}</option>)}
          </select>
          <div className="mt-2 text-xs text-muted-foreground">Model: {app.defaultModel} | Thinking: {app.thinkingLevel}</div>
        </Section>

        {/* Budget */}
        <Section icon={DollarSign} title="预算">
          <div className="flex items-center gap-4">
            <input type="number" value={app.costBudget} onChange={e => updateApp({ costBudget: +e.target.value })}
              className="w-24 px-3 py-2 border border-border rounded-lg bg-background text-sm" />
            <span className="text-sm text-muted-foreground">USD / 月</span>
          </div>
        </Section>
      </div>
    </div>
  )
}

function Section({ icon: Icon, title, children }: { icon: any; title: string; children: React.ReactNode }) {
  return (
    <div className="glass-card !rounded-xl p-5">
      <div className="flex items-center gap-2 mb-3 text-sm font-semibold">
        <Icon size={16} className="text-primary" /> {title}
      </div>
      {children}
    </div>
  )
}

// aitest/web/src/views/SettingsView.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { usePreferences } from '@/composables/usePreferences'
import { Languages, Sun, Moon, Palette, Server } from 'lucide-vue-next'

const { t } = useI18n()
const { currentTheme, isDark, lang, themeNames, setTheme, toggleDark, setLang } = usePreferences()

const providers = ['claude', 'deepseek', 'google']
const currentProvider = ref(localStorage.getItem('tlo-provider') || 'claude')
const auditInterval = ref(localStorage.getItem('tlo-audit-interval') || '86400')

function saveProvider() {
  localStorage.setItem('tlo-provider', currentProvider.value)
  localStorage.setItem('tlo-audit-interval', auditInterval.value)
  ;(window as any).__tlo_toast?.add(t('settings.saved'), 'success')
}
</script>

<template>
  <div class="max-w-[560px] space-y-5">
    <!-- Language -->
    <div class="glass-card !rounded-xl p-5">
      <h3 class="text-sm font-semibold mb-4 flex items-center gap-2"><Languages :size="16" :stroke-width="2" class="text-primary" /> {{ t('lang.label') }}</h3>
      <div class="flex gap-2">
        <button
          @click="setLang('zh')"
          :class="['flex-1 py-3 rounded-lg text-sm font-semibold cursor-pointer border transition-all font-sans',
            lang === 'zh' ? 'btn-primary' : 'btn-outline']"
        >🇨🇳 中文</button>
        <button
          @click="setLang('en')"
          :class="['flex-1 py-3 rounded-lg text-sm font-semibold cursor-pointer border transition-all font-sans',
            lang === 'en' ? 'btn-primary' : 'btn-outline']"
        >🇺🇸 English</button>
      </div>
    </div>

    <!-- Appearance -->
    <div class="glass-card !rounded-xl p-5">
      <h3 class="text-sm font-semibold mb-4 flex items-center gap-2"><Palette :size="16" :stroke-width="2" class="text-primary" /> Appearance</h3>

      <!-- Dark/Light -->
      <div class="flex gap-2 mb-4">
        <button @click="toggleDark" :class="['flex-1 flex items-center justify-center gap-2 py-3 rounded-lg text-sm font-semibold cursor-pointer border transition-all font-sans', !isDark ? 'btn-primary' : 'btn-outline']">
          <Sun :size="15" /> Light
        </button>
        <button @click="toggleDark" :class="['flex-1 flex items-center justify-center gap-2 py-3 rounded-lg text-sm font-semibold cursor-pointer border transition-all font-sans', isDark ? 'btn-primary' : 'btn-outline']">
          <Moon :size="15" /> Dark
        </button>
      </div>

      <!-- Theme grid -->
      <div class="text-xs text-muted-foreground mb-2.5 font-semibold uppercase tracking-wider">Color Theme</div>
      <div class="grid grid-cols-4 gap-2">
        <button v-for="name in themeNames" :key="name" @click="setTheme(name)"
          :class="['py-2.5 rounded-lg text-xs font-semibold cursor-pointer border transition-all font-sans capitalize',
            currentTheme === name ? 'border-primary text-primary bg-primary/10 shadow-sm' : 'btn-outline opacity-70']"
        >{{ name }}</button>
      </div>
    </div>

    <!-- Provider -->
    <div class="glass-card !rounded-xl p-5">
      <h3 class="text-sm font-semibold mb-4 flex items-center gap-2"><Server :size="16" :stroke-width="2" class="text-primary" /> {{ t('settings.provider') }}</h3>
      <div class="space-y-3.5">
        <div>
          <label class="block text-xs font-semibold mb-1.5 text-muted-foreground">LLM Provider</label>
          <select v-model="currentProvider" class="w-full px-3 py-2.5 rounded-lg border text-sm bg-card text-foreground outline-none focus:border-ring transition-colors font-sans">
            <option v-for="p in providers" :key="p" :value="p">{{ p === 'claude' ? 'Anthropic Claude' : p === 'deepseek' ? 'DeepSeek' : 'Google Gemini' }}</option>
          </select>
        </div>
        <div>
          <label class="block text-xs font-semibold mb-1.5 text-muted-foreground">{{ t('settings.interval') }}</label>
          <input v-model="auditInterval" type="number" class="w-full px-3 py-2.5 rounded-lg border text-sm bg-card text-foreground outline-none focus:border-ring transition-colors font-mono" />
        </div>
        <button @click="saveProvider" class="btn-primary w-full">{{ t('settings.save') }}</button>
      </div>
    </div>
  </div>
</template>
