// aitest/web/src/views/OnboardingWizardView.vue
<script setup lang="ts">
import { computed, onUnmounted } from 'vue'
import { useRouter } from 'vue-router'
import { useOnboardingStore } from '@/stores/onboarding'
import { useOnboardingWS } from '@/composables/useOnboardingWS'
import StepChooseSource from '@/components/onboarding/StepChooseSource.vue'
import StepUrlInput from '@/components/onboarding/StepUrlInput.vue'
import StepScanning from '@/components/onboarding/StepScanning.vue'
import StepConfirmMenu from '@/components/onboarding/StepConfirmMenu.vue'
import StepResults from '@/components/onboarding/StepResults.vue'
import { Globe, Wifi, ListTree, FileSearch, CheckCircle2, AlertTriangle, ArrowRight, FolderOpen } from 'lucide-vue-next'
import { ref } from 'vue'

const store = useOnboardingStore()
const router = useRouter()
const { disconnect, wsError } = useOnboardingWS()

const sourceChosen = ref(false)

const STEPS = [
  { key: 'source', label: 'Source', icon: FolderOpen },
  { key: 'discovery', label: 'Discovery', icon: Wifi },
  { key: 'confirm', label: 'Review', icon: ListTree },
  { key: 'results', label: 'Results', icon: CheckCircle2 },
]

const currentStepIndex = computed(() => {
  if (store.isComplete) return 3
  if (store.isMenuReady) return 2
  if (store.isRunning || sourceChosen.value) return 1
  return 0
})

function onSourceChoose(type: 'url' | 'local', value: string) {
  store.sourceType = type
  if (type === 'local') {
    store.projectPath = value
    store.baseUrl = value  // Show path in UI
    // Derive project ID from folder name
    const parts = value.replace(/\\/g, '/').replace(/\/$/, '').split('/')
    const folderName = parts[parts.length - 1] || 'local-project'
    store.projectId = folderName
    store.start(value, folderName, '', '')
  } else {
    store.baseUrl = value
  }
  sourceChosen.value = true
}

function openProject() {
  router.push({ path: '/kanban', query: { project: store.projectId } })
}

onUnmounted(() => {
  disconnect()
})
</script>

<template>
  <div class="onboarding-wizard">
    <!-- Header -->
    <header class="wizard-header">
      <h2>New Project Onboarding</h2>
      <p class="subtitle">Enter a URL — TLO auto-discovers the application structure</p>
    </header>

    <!-- Step indicators -->
    <nav class="step-indicators">
      <div
        v-for="(step, i) in STEPS"
        :key="step.key"
        class="step-dot"
        :class="{
          active: i === currentStepIndex,
          done: i < currentStepIndex,
          error: store.isFailed && i === currentStepIndex,
        }"
      >
        <component :is="step.icon" :size="18" />
        <span class="step-label">{{ step.label }}</span>
      </div>
    </nav>

    <!-- Progress bar -->
    <div v-if="store.isRunning || store.isComplete" class="progress-bar-wrapper">
      <div class="progress-bar">
        <div
          class="progress-fill"
          :class="{ complete: store.isComplete, error: store.isFailed }"
          :style="{ width: (store.progress * 100) + '%' }"
        />
      </div>
      <span class="progress-text">{{ Math.round(store.progress * 100) }}%</span>
    </div>

    <!-- Error banner -->
    <div v-if="wsError" class="error-banner">
      <AlertTriangle :size="16" />
      <span>{{ wsError }}</span>
    </div>

    <!-- Step content -->
    <main class="wizard-body">
      <!-- Step 0: Choose source -->
      <StepChooseSource
        v-if="currentStepIndex === 0 && !sourceChosen"
        @choose="onSourceChoose"
      />
      <!-- Step 0.5: URL input (only for URL source) -->
      <StepUrlInput
        v-else-if="currentStepIndex === 1 && !store.isRunning && store.sourceType === 'url'"
      />
      <!-- Step 1: Discovery scanning -->
      <StepScanning v-else-if="currentStepIndex === 1 && store.isRunning" />
      <!-- Step 2: Menu confirmation -->
      <StepConfirmMenu v-else-if="currentStepIndex === 2" />
      <!-- Step 3: Results -->
      <StepResults v-else-if="currentStepIndex === 3" />

      <!-- Failed state -->
      <div v-if="store.isFailed" class="failed-state">
        <AlertTriangle :size="48" class="error-icon" />
        <h3>Onboarding failed</h3>
        <ul v-if="store.errors.length" class="error-list">
          <li v-for="(err, i) in store.errors" :key="i">{{ err }}</li>
        </ul>
        <div class="btn-row">
          <button class="btn btn-secondary" @click="store.reset()">Try Again</button>
        </div>
      </div>
    </main>

    <!-- Footer actions -->
    <footer class="wizard-footer">
      <button
        v-if="store.isRunning || store.isMenuReady"
        class="btn btn-outline"
        @click="store.cancel()"
      >
        Cancel
      </button>
      <button
        v-if="store.isComplete"
        class="btn btn-primary"
        @click="openProject"
      >
        Open Project <ArrowRight :size="16" />
      </button>
    </footer>
  </div>
</template>

<style scoped>
.onboarding-wizard {
  max-width: 720px;
  margin: 0 auto;
  padding: 32px 24px;
  animation: fade-in 0.3s ease-out;
}

.wizard-header {
  margin-bottom: 32px;
  text-align: center;
}
.wizard-header h2 {
  font-size: 1.5rem;
  font-weight: 700;
  color: var(--foreground);
  margin: 0 0 8px;
}
.subtitle {
  color: var(--muted-foreground);
  font-size: 0.9rem;
  margin: 0;
}

/* Step indicators */
.step-indicators {
  display: flex;
  justify-content: center;
  gap: 40px;
  margin-bottom: 24px;
}
.step-dot {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 6px;
  color: var(--muted-foreground);
  transition: color 0.2s;
}
.step-dot.active {
  color: var(--primary);
}
.step-dot.done {
  color: var(--success);
}
.step-dot.error {
  color: var(--destructive);
}
.step-label {
  font-size: 0.75rem;
  font-weight: 500;
}

/* Progress bar */
.progress-bar-wrapper {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-bottom: 24px;
}
.progress-bar {
  flex: 1;
  height: 6px;
  background: var(--secondary);
  border-radius: var(--radius-full);
  overflow: hidden;
}
.progress-fill {
  height: 100%;
  background: var(--primary);
  border-radius: var(--radius-full);
  transition: width 0.5s ease;
}
.progress-fill.complete {
  background: var(--success);
}
.progress-fill.error {
  background: var(--destructive);
}
.progress-text {
  font-size: 0.8rem;
  font-weight: 600;
  color: var(--muted-foreground);
  min-width: 3em;
  text-align: right;
}

/* Body */
.wizard-body {
  min-height: 300px;
}

/* Footer */
.wizard-footer {
  display: flex;
  justify-content: flex-end;
  gap: 12px;
  margin-top: 24px;
  padding-top: 16px;
  border-top: 1px solid var(--border);
}

/* Error */
.error-banner {
  display: flex;
  align-items: center;
  gap: 8px;
  background: var(--warning-light);
  color: var(--warning);
  padding: 8px 16px;
  border-radius: var(--radius-md);
  margin-bottom: 16px;
  font-size: 0.85rem;
}
.failed-state {
  text-align: center;
  padding: 48px 0;
}
.error-icon {
  color: var(--destructive);
  margin-bottom: 16px;
}
.failed-state h3 {
  margin: 0 0 16px;
  color: var(--destructive);
}
.error-list {
  list-style: none;
  padding: 0;
  color: var(--muted-foreground);
  font-size: 0.85rem;
}
.error-list li {
  padding: 4px 0;
}

/* Buttons */
.btn {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 10px 24px;
  border-radius: var(--radius-md);
  font-size: 0.9rem;
  font-weight: 500;
  cursor: pointer;
  border: none;
  transition: background 0.15s, color 0.15s;
}
.btn-primary {
  background: var(--primary);
  color: var(--primary-foreground);
}
.btn-primary:hover { filter: brightness(1.1); }
.btn-secondary {
  background: var(--secondary);
  color: var(--secondary-foreground);
}
.btn-outline {
  background: transparent;
  border: 1px solid var(--border);
  color: var(--muted-foreground);
}
.btn-outline:hover {
  background: var(--secondary);
}
.btn-row {
  display: flex;
  gap: 12px;
  justify-content: center;
  margin-top: 16px;
}

@keyframes fade-in {
  from { opacity: 0; transform: translateY(8px); }
  to   { opacity: 1; transform: translateY(0); }
}
</style>

// aitest/web/src/views/cross-cutting/OnboardingWizardView.tsx
/** Onboarding Wizard — multi-step project discovery. shadcn/ui edition. */
import { useState, useMemo, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { useOnboardingStore, selectIsComplete, selectIsMenuReady, selectIsFailed, getStoredSession } from '@/stores/onboarding'
import { useOnboardingWS } from '@/hooks/useOnboardingWS'
import StepChooseSource from '@/components/onboarding/StepChooseSource'
import StepUrlInput from '@/components/onboarding/StepUrlInput'
import StepScanning from '@/components/onboarding/StepScanning'
import StepConfirmMenu from '@/components/onboarding/StepConfirmMenu'
import StepResults from '@/components/onboarding/StepResults'
import { Button } from '@/components/ui/button'
import { Progress } from '@/components/ui/progress'
import { cn } from '@/lib/utils'
import { Globe, Wifi, ListTree, FileSearch, CheckCircle2, AlertTriangle, ArrowRight, FolderOpen } from 'lucide-react'

export default function OnboardingWizardView() {
  const navigate = useNavigate()
  const { t } = useTranslation()
  const store = useOnboardingStore
  const isRunning = useOnboardingStore(s => s.isRunning)
  const isComplete = useOnboardingStore(selectIsComplete)
  const isMenuReady = useOnboardingStore(selectIsMenuReady)
  const isFailed = useOnboardingStore(selectIsFailed)
  const isCancelled = useOnboardingStore(s => s.step === 'cancelled')
  const progress = useOnboardingStore(s => s.progress)
  const errors = useOnboardingStore(s => s.errors)
  const sourceType = useOnboardingStore(s => s.sourceType)
  const projectId = useOnboardingStore(s => s.projectId)
  const checkpoint = useOnboardingStore(s => s.checkpoint)
  const baseUrl = useOnboardingStore(s => s.baseUrl)
  const start = useOnboardingStore(s => s.start)
  const cancel = useOnboardingStore(s => s.cancel)
  const reset = useOnboardingStore(s => s.reset)
  const restore = useOnboardingStore(s => s.restore)
  const pollStatus = useOnboardingStore(s => s.pollStatus)
  const { disconnect, wsError } = useOnboardingWS()
  const steps = [
    { key: 'source', label: t('onboarding.step_source'), icon: FolderOpen },
    { key: 'discovery', label: t('onboarding.step_discovery'), icon: Wifi },
    { key: 'confirm', label: t('onboarding.step_review'), icon: ListTree },
    { key: 'results', label: t('onboarding.step_results'), icon: CheckCircle2 },
  ]

  const [sourceChosen, setSourceChosen] = useState(false)
  const [restored, setRestored] = useState(false)

  // Restore session on mount (page refresh recovery)
  useEffect(() => {
    const saved = getStoredSession()
    if (saved && saved.sessionId && !restored) {
      restore(saved)
      setSourceChosen(true)
      setRestored(true)
      // Resume polling immediately
      pollStatus()
    }
  }, [restore, pollStatus, restored])

  const currentStepIndex = useMemo(() => {
    if (isComplete) return 3
    if (isMenuReady) return 2
    if (isRunning || sourceChosen) return 1
    return 0
  }, [isComplete, isMenuReady, isRunning, sourceChosen])

  function onSourceChoose(type: 'url' | 'local', value: string) {
    store.setState({ sourceType: type })
    if (type === 'local') {
      const s = useOnboardingStore.getState()
      s.projectPath = value
      s.baseUrl = value
      const parts = value.replace(/\\/g, '/').replace(/\/$/, '').split('/')
      const folderName = parts[parts.length - 1] || 'local-project'
      store.setState({ projectPath: value, baseUrl: value, projectId: folderName })
      s.start(value, folderName, '', '')
    } else {
      store.setState({ baseUrl: value })
    }
    setSourceChosen(true)
  }

  function handleBack() {
    // Only back from URL input to source selection (before scanning starts)
    if (currentStepIndex === 1 && !isRunning && sourceType === 'url') {
      setSourceChosen(false)
      store.setState({ baseUrl: '' })
    }
  }

  function openProject() {
    navigate(`/projects/${projectId}/kanban`)
  }

  useEffect(() => {
    return () => { disconnect() }
  }, [disconnect])

  return (
    <div className="max-w-[720px] mx-auto py-8 px-6 animate-[fade-in_0.3s_ease-out]">
      <header className="mb-8 text-center">
        <h2 className="text-2xl font-bold text-foreground mb-2">{t('onboarding.wizard_title')}</h2>
        <p className="text-sm text-muted-foreground m-0">
          {t('onboarding.wizard_desc')}
        </p>
      </header>

      {/* Step indicators */}
      <nav className="flex justify-center gap-10 mb-6">
        {steps.map((step, i) => (
          <div key={step.key}
            className={cn(
              'flex flex-col items-center gap-1.5 transition-colors',
              i === currentStepIndex ? 'text-primary' :
              i < currentStepIndex ? 'text-success' :
              'text-muted-foreground',
              isFailed && i === currentStepIndex && 'text-destructive'
            )}
          >
            <step.icon size={18} />
            <span className="text-xs font-medium">{step.label}</span>
          </div>
        ))}
      </nav>

      {/* Progress bar */}
      {(isRunning || isComplete) && (
        <div className="flex items-center gap-3 mb-6">
          <Progress
            value={Math.round(progress * 100)}
            className={cn(isComplete && '[&>div]:bg-success', isFailed && '[&>div]:bg-destructive')}
          />
          <span className="text-xs font-semibold text-muted-foreground min-w-[3em] text-right">
            {Math.round(progress * 100)}%
          </span>
        </div>
      )}

      {wsError && (
        <div className="flex items-center gap-2 bg-warning-light text-warning px-4 py-2 rounded-lg mb-4 text-sm">
          <AlertTriangle size={16} />
          <span>{/api[_ -]?key|api key/i.test(wsError) ? t('onboarding.api_key_error') : wsError}</span>
        </div>
      )}

      <main className="min-h-[300px]">
        {!isCancelled && (
          <>
        {currentStepIndex === 0 && !sourceChosen && <StepChooseSource onChoose={onSourceChoose} />}
        {currentStepIndex === 1 && !isRunning && sourceType === 'url' && <StepUrlInput />}
        {currentStepIndex === 1 && isRunning && <StepScanning />}
        {currentStepIndex === 2 && <StepConfirmMenu />}
        {currentStepIndex === 3 && <StepResults />}
          </>
        )}
        {isFailed && (
          <div className="text-center py-12">
            <AlertTriangle size={48} className="text-destructive mb-4 mx-auto" />
            <h3 className="text-destructive mb-4">{t('onboarding.onboarding_failed')}</h3>
            {errors.length > 0 && (
              <ul className="list-none p-0 text-muted-foreground text-sm">
                {errors.map((err, i) => <li key={i} className="py-1">{err}</li>)}
              </ul>
            )}
            <div className="flex gap-3 justify-center mt-4">
              <Button variant="secondary" onClick={() => reset()}>{t('onboarding.try_again')}</Button>
            </div>
          </div>
        )}
        {isCancelled && (
          <div className="text-center py-12">
            <FolderOpen size={48} className="text-warning mb-4 mx-auto" />
            <h3 className="text-warning mb-2">{t('onboarding.onboarding_cancelled')}</h3>
            <p className="text-muted-foreground text-sm mb-4">
              {checkpoint
                ? `Partial results saved — ${checkpoint.pages?.length || 0} pages discovered. You can resume from where you left off.`
                : t('onboarding.no_partial_results')}
            </p>
            <div className="flex gap-3 justify-center mt-4">
              {checkpoint && (
                <Button variant="gradient" onClick={() => {
                  start(baseUrl, projectId, '', '', '', true)
                  setSourceChosen(true)
                }}>
                  {t('onboarding.resume_progress')} <ArrowRight size={16} />
                </Button>
              )}
              <Button variant="secondary" onClick={() => reset()}>{t('onboarding.restart')}</Button>
            </div>
          </div>
        )}
      </main>

      <footer className="flex justify-between gap-3 mt-6 pt-4 border-t border-border">
        <div>
          {/* Back button: only from URL input → source selection */}
          {currentStepIndex === 1 && !isRunning && sourceType === 'url' && (
            <Button variant="outline" onClick={handleBack}>← 上一步</Button>
          )}
        </div>
        <div className="flex gap-3">
        {(isRunning || isMenuReady) && <Button variant="outline" onClick={() => cancel()}>{t('onboarding.cancel')}</Button>}
        {isComplete && (
          <Button variant="gradient" onClick={openProject}>
            {t('onboarding.open_project')} <ArrowRight size={16} />
          </Button>
        )}
        </div>
      </footer>
    </div>
  )
}
