// aitest/web/src/components/SidebarNav.tsx
/** Segmented sidebar: Dashboard | Workspace (per-project) | Bottom actions.
 *  shadcn/ui edition — Button + Collapsible + Separator.
 */
import { useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { useProjectStore } from '../stores/project'
import { useSettingsStore } from '../stores/settings'
import {
  LayoutDashboard, LayoutGrid, Search, MessageSquare, Play,
  BarChart3, BookOpen, Settings, Plus, FolderOpen, Terminal,
  Lightbulb, Link2, Clock, Eye, ChevronDown, Moon, Zap, TreePine,
} from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Separator } from '@/components/ui/separator'
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible'
import { cn } from '@/lib/utils'

interface SidebarNavProps {
  currentView: string
  onNavigate: (view: string) => void
}

type TierItem = { id: string; icon: any; key: string }

const tier1Items: TierItem[] = [
  { id: 'execution', icon: Play, key: '执行中心' },
  { id: 'artifacts', icon: FolderOpen, key: '产物' },
]

const tier2Items: TierItem[] = [
  { id: 'observability', icon: Clock, key: '可观测性' },
  { id: 'reports', icon: BarChart3, key: '报告' },
  { id: 'knowledge', icon: BookOpen, key: '知识' },
  { id: 'kanban', icon: LayoutGrid, key: '看板' },
]

const tier3Items: TierItem[] = [
  { id: 'terminal', icon: Terminal, key: '终端' },
  { id: 'gaps', icon: Search, key: '缺口' },
  { id: 'chat', icon: MessageSquare, key: '对话' },
  { id: 'settings', icon: Settings, key: '设置' },
]

function currentSection(view: string): 'dashboard' | 'project' | 'bottom' {
  if (view === 'dashboard') return 'dashboard'
  if (view === 'onboarding') return 'bottom'
  if (view === 'settings') return 'bottom'
  return 'project'
}

const themeIcon: Record<string, any> = {
  default:   Moon,
  aoko:      Zap,
  soujuurou: TreePine,
}

export default function SidebarNav({ currentView, onNavigate }: SidebarNavProps) {
  const { t } = useTranslation()
  const activeId = useProjectStore(s => s.activeId)
  const activeProject = useProjectStore(s => s.activeProject())
  const hasActiveProject = !!activeId
  const pid = activeId || 'default'
  const [toolsOpen, setToolsOpen] = useState(false)
  const theme = useSettingsStore(s => s.app.theme)
  const LogoIcon = themeIcon[theme] || Moon

  const hasProjectData = useMemo(() => {
    try {
      const mods = JSON.parse(localStorage.getItem('tlo-modules') || '{}')
      return Object.keys(mods).length > 0
    } catch { return false }
  }, [])

  const section = currentSection(currentView)
  const projectActive = (itemId: string) => currentView === itemId

  const NavBtn = ({ active, onClick, icon: Icon, label }: {
    active: boolean; onClick: () => void; icon: any; label: string
  }) => (
    <Button
      variant="ghost"
      size="sm"
      onClick={onClick}
      className={cn(
        'justify-start gap-3 w-full h-9 px-3 text-[13px] font-medium',
        active
          ? 'bg-sidebar-active-bg text-sidebar-active [&>svg]:stroke-[2.5]'
          : 'text-sidebar-foreground hover:bg-sidebar-active-bg/50 [&>svg]:stroke-[1.8]'
      )}
    >
      <Icon size={18} className="shrink-0" />
      <span className="truncate">{label}</span>
    </Button>
  )

  return (
    <aside className="w-[232px] flex flex-col shrink-0 select-none border-r border-sidebar-border bg-sidebar">
      {/* Logo */}
      <div className="px-5 py-4 flex items-center gap-2.5 border-b border-sidebar-border">
        <div className="w-7 h-7 rounded-lg flex items-center justify-center"
          style={{ background: 'var(--primary-gradient)' }}>
          <LogoIcon size={14} className="text-white" strokeWidth={2.5} />
        </div>
        <span className="text-[15px] font-bold text-sidebar-logo">
          TLO<span className="font-light opacity-50"> Platform</span>
        </span>
      </div>

      <nav className="flex-1 p-2.5 flex flex-col overflow-y-auto gap-0.5">
        {/* Dashboard */}
        <NavBtn
          active={section === 'dashboard'}
          onClick={() => onNavigate('/dashboard')}
          icon={LayoutDashboard}
          label="面板"
        />

        <div className="h-px mx-2 my-2 bg-sidebar-border opacity-60" />

        {/* Workspace */}
        {hasActiveProject ? (
          <div className="mt-1">
            <div className="flex items-center gap-1.5 px-3 py-1.5 text-[11px] font-semibold text-sidebar-foreground/50 uppercase tracking-wider">
              <FolderOpen size={12} />
              <span className="truncate">{activeProject?.name || activeProject?.id || 'Workspace'}</span>
            </div>

            {tier1Items.map(item => (
              <NavBtn
                key={item.id}
                active={projectActive(item.id)}
                onClick={() => onNavigate(`/projects/${pid}/${item.id}`)}
                icon={item.icon}
                label={item.key}
              />
            ))}

            {hasProjectData && (
              <>
                <div className="h-px mx-3 my-1 bg-sidebar-border opacity-40" />
                {tier2Items.map(item => (
                  <NavBtn
                    key={item.id}
                    active={projectActive(item.id)}
                    onClick={() => onNavigate(`/projects/${pid}/${item.id}`)}
                    icon={item.icon}
                    label={item.key}
                  />
                ))}
              </>
            )}

            {/* Tier 3: collapsible */}
            <Collapsible open={toolsOpen} onOpenChange={setToolsOpen} className="mt-1">
              <CollapsibleTrigger asChild>
                <button className={cn(
                  'flex items-center gap-1 w-full px-3 py-1 text-[10px] uppercase tracking-wider text-sidebar-foreground/40 hover:text-sidebar-foreground/70 transition-colors cursor-pointer',
                  toolsOpen && 'text-sidebar-foreground/60'
                )}>
                  <ChevronDown size={10} className={cn('transition-transform', toolsOpen && 'rotate-180')} />
                  更多工具
                </button>
              </CollapsibleTrigger>
              <CollapsibleContent>
                {tier3Items.map(item => (
                  <NavBtn
                    key={item.id}
                    active={projectActive(item.id)}
                    onClick={() => onNavigate(`/projects/${pid}/${item.id}`)}
                    icon={item.icon}
                    label={item.key}
                  />
                ))}
              </CollapsibleContent>
            </Collapsible>
          </div>
        ) : (
          <div className="flex flex-col items-center gap-2 py-8 px-4 text-center">
            <FolderOpen size={24} className="opacity-30" />
            <p className="text-xs text-muted-foreground m-0">选择一个项目以查看工作区</p>
            <button onClick={() => onNavigate('/dashboard')} className="text-xs text-primary bg-transparent border-none cursor-pointer hover:underline">
              前往面板
            </button>
          </div>
        )}
      </nav>

      {/* Bottom actions */}
      <div className="p-2.5 flex flex-col gap-0.5 border-t border-sidebar-border">
        <NavBtn
          active={currentView === 'onboarding'}
          onClick={() => onNavigate('/onboarding')}
          icon={Plus}
          label={t('nav.onboarding')}
        />
        <NavBtn
          active={currentView === 'settings'}
          onClick={() => onNavigate('/settings')}
          icon={Settings}
          label={t('nav.settings')}
        />
      </div>
    </aside>
  )
}

// aitest/web/src/components/SidebarNav.vue
<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { LayoutGrid, Search, MessageSquare, Map, Play, BarChart3, BookOpen, Settings } from 'lucide-vue-next'

const { t } = useI18n()
defineProps<{ currentView: string }>()
const emit = defineEmits<{ navigate: [view: string] }>()

const navItems = [
  { id: 'kanban', icon: LayoutGrid, key: 'nav.kanban' },
  { id: 'gaps', icon: Search, key: 'nav.gaps' },
  { id: 'chat', icon: MessageSquare, key: 'nav.chat' },
  { id: 'strategy', icon: Map, key: 'nav.strategy' },
  { id: 'execution', icon: Play, key: 'nav.execution' },
  { id: 'reports', icon: BarChart3, key: 'nav.reports' },
  { id: 'knowledge', icon: BookOpen, key: 'nav.knowledge' },
]
</script>

<template>
  <aside class="w-[232px] flex flex-col flex-shrink-0 select-none border-r" style="background:var(--sidebar); border-color:var(--sidebar-border)">
    <div class="px-5 py-4 flex items-center gap-2.5" style="border-bottom:1px solid var(--sidebar-border)">
      <div class="w-7 h-7 rounded-lg flex items-center justify-center" style="background:var(--primary-gradient)">
        <Play class="w-3.5 h-3.5 text-white" fill="white" :stroke-width="3" />
      </div>
      <span class="text-[15px] font-bold" style="color:var(--sidebar-logo)">TLO<span class="font-light opacity-50"> Platform</span></span>
    </div>

    <nav class="flex-1 p-2.5 flex flex-col gap-0.5 overflow-y-auto">
      <button v-for="item in navItems" :key="item.id" @click="emit('navigate', item.id)"
        :style="currentView === item.id
          ? { background: 'var(--sidebar-active-bg)', color: 'var(--sidebar-active)' }
          : { background: 'transparent', color: 'var(--sidebar-foreground)' }"
        class="flex items-center gap-3 px-3 py-2 rounded-lg text-[13px] transition-all w-full text-left border-none cursor-pointer font-sans font-medium"
      >
        <component :is="item.icon" :size="18" :stroke-width="currentView === item.id ? 2.5 : 1.8" class="flex-shrink-0" />
        <span class="truncate">{{ t(item.key) }}</span>
      </button>
    </nav>

    <!-- Settings at bottom -->
    <div class="p-2.5" style="border-top:1px solid var(--sidebar-border)">
      <button @click="emit('navigate', 'settings')"
        :style="currentView === 'settings'
          ? { background: 'var(--sidebar-active-bg)', color: 'var(--sidebar-active)' }
          : { background: 'transparent', color: 'var(--sidebar-foreground)' }"
        class="flex items-center gap-3 px-3 py-2 rounded-lg text-[13px] transition-all w-full text-left border-none cursor-pointer font-sans font-medium"
      >
        <component :is="Settings" :size="18" :stroke-width="currentView === 'settings' ? 2.5 : 1.8" class="flex-shrink-0" />
        <span class="truncate">{{ t('nav.settings') }}</span>
      </button>
    </div>
  </aside>
</template>
