// aitest/web/src/views/SettingsView.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { usePreferences } from '@/composables/usePreferences'
import { Languages, Sun, Moon, Palette, Server } from 'lucide-vue-next'

const { t } = useI18n()
const { currentTheme, isDark, lang, themeNames, setTheme, toggleDark, setLang } = usePreferences()

const providers = ['claude', 'deepseek', 'google']
const currentProvider = ref(localStorage.getItem('tlo-provider') || 'claude')
const auditInterval = ref(localStorage.getItem('tlo-audit-interval') || '86400')

function saveProvider() {
  localStorage.setItem('tlo-provider', currentProvider.value)
  localStorage.setItem('tlo-audit-interval', auditInterval.value)
  ;(window as any).__tlo_toast?.add(t('settings.saved'), 'success')
}
</script>

<template>
  <div class="max-w-[560px] space-y-5">
    <!-- Language -->
    <div class="glass-card !rounded-xl p-5">
      <h3 class="text-sm font-semibold mb-4 flex items-center gap-2"><Languages :size="16" :stroke-width="2" class="text-primary" /> {{ t('lang.label') }}</h3>
      <div class="flex gap-2">
        <button
          @click="setLang('zh')"
          :class="['flex-1 py-3 rounded-lg text-sm font-semibold cursor-pointer border transition-all font-sans',
            lang === 'zh' ? 'btn-primary' : 'btn-outline']"
        >🇨🇳 中文</button>
        <button
          @click="setLang('en')"
          :class="['flex-1 py-3 rounded-lg text-sm font-semibold cursor-pointer border transition-all font-sans',
            lang === 'en' ? 'btn-primary' : 'btn-outline']"
        >🇺🇸 English</button>
      </div>
    </div>

    <!-- Appearance -->
    <div class="glass-card !rounded-xl p-5">
      <h3 class="text-sm font-semibold mb-4 flex items-center gap-2"><Palette :size="16" :stroke-width="2" class="text-primary" /> Appearance</h3>

      <!-- Dark/Light -->
      <div class="flex gap-2 mb-4">
        <button @click="toggleDark" :class="['flex-1 flex items-center justify-center gap-2 py-3 rounded-lg text-sm font-semibold cursor-pointer border transition-all font-sans', !isDark ? 'btn-primary' : 'btn-outline']">
          <Sun :size="15" /> Light
        </button>
        <button @click="toggleDark" :class="['flex-1 flex items-center justify-center gap-2 py-3 rounded-lg text-sm font-semibold cursor-pointer border transition-all font-sans', isDark ? 'btn-primary' : 'btn-outline']">
          <Moon :size="15" /> Dark
        </button>
      </div>

      <!-- Theme grid -->
      <div class="text-xs text-muted-foreground mb-2.5 font-semibold uppercase tracking-wider">Color Theme</div>
      <div class="grid grid-cols-4 gap-2">
        <button v-for="name in themeNames" :key="name" @click="setTheme(name)"
          :class="['py-2.5 rounded-lg text-xs font-semibold cursor-pointer border transition-all font-sans capitalize',
            currentTheme === name ? 'border-primary text-primary bg-primary/10 shadow-sm' : 'btn-outline opacity-70']"
        >{{ name }}</button>
      </div>
    </div>

    <!-- Provider -->
    <div class="glass-card !rounded-xl p-5">
      <h3 class="text-sm font-semibold mb-4 flex items-center gap-2"><Server :size="16" :stroke-width="2" class="text-primary" /> {{ t('settings.provider') }}</h3>
      <div class="space-y-3.5">
        <div>
          <label class="block text-xs font-semibold mb-1.5 text-muted-foreground">LLM Provider</label>
          <select v-model="currentProvider" class="w-full px-3 py-2.5 rounded-lg border text-sm bg-card text-foreground outline-none focus:border-ring transition-colors font-sans">
            <option v-for="p in providers" :key="p" :value="p">{{ p === 'claude' ? 'Anthropic Claude' : p === 'deepseek' ? 'DeepSeek' : 'Google Gemini' }}</option>
          </select>
        </div>
        <div>
          <label class="block text-xs font-semibold mb-1.5 text-muted-foreground">{{ t('settings.interval') }}</label>
          <input v-model="auditInterval" type="number" class="w-full px-3 py-2.5 rounded-lg border text-sm bg-card text-foreground outline-none focus:border-ring transition-colors font-mono" />
        </div>
        <button @click="saveProvider" class="btn-primary w-full">{{ t('settings.save') }}</button>
      </div>
    </div>
  </div>
</template>

// aitest/web/src/views/global/SettingsView.tsx
/** App Settings — shadcn/ui edition. Theme, language, provider, budget. */
import { useSettingsStore } from '../../stores/settings'
import { Settings, Palette, Globe, Cpu, DollarSign } from 'lucide-react'
import { useTranslation } from 'react-i18next'
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card'
import { ToggleGroup, ToggleGroupItem } from '@/components/ui/toggle-group'
import { Checkbox } from '@/components/ui/checkbox'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'

const themes = [
  { value: 'alice', label: 'Alice — Winter Mansion' },
  { value: 'aoko', label: 'Aoko — Clear Sky' },
  { value: 'soujuurou', label: 'Soujuurou — Mountain Wood' },
]

export default function SettingsView() {
  const { t, i18n } = useTranslation()
  const app = useSettingsStore(s => s.app)
  const updateApp = useSettingsStore(s => s.updateApp)

  const applyTheme = (name: string) => {
    updateApp({ theme: name })
    localStorage.setItem('tlo-theme-name', name)
    document.documentElement.setAttribute('data-theme', name)
  }

  const applyDark = (checked: boolean) => {
    updateApp({ darkMode: checked })
    document.documentElement.classList.toggle('dark', checked)
    localStorage.setItem('tlo-theme', checked ? 'dark' : 'light')
  }

  const applyLang = (lang: string) => {
    i18n.changeLanguage(lang)
    localStorage.setItem('tlo-lang', lang)
  }

  return (
    <div className="p-6 max-w-2xl">
      <h1 className="text-xl font-bold mb-6 flex items-center gap-2">
        <Settings size={20} /> {t('settings.title')}
      </h1>

      <div className="space-y-6">
        {/* Appearance */}
        <Card>
          <CardHeader>
            <CardTitle className="text-sm flex items-center gap-2">
              <Palette size={16} className="text-primary" /> 外观
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <ToggleGroup type="single" value={app.theme} onValueChange={v => v && applyTheme(v)}
              className="grid grid-cols-3 gap-2">
              {themes.map(t => (
                <ToggleGroupItem key={t.value} value={t.value} className="text-xs h-8">
                  {t.label}
                </ToggleGroupItem>
              ))}
            </ToggleGroup>
            <div className="flex items-center gap-2">
              <Checkbox id="dark-mode" checked={app.darkMode}
                onCheckedChange={v => applyDark(v === true)} />
              <Label htmlFor="dark-mode" className="cursor-pointer text-sm">
                {t('theme.dark')}
              </Label>
            </div>
          </CardContent>
        </Card>

        {/* Language */}
        <Card>
          <CardHeader>
            <CardTitle className="text-sm flex items-center gap-2">
              <Globe size={16} className="text-primary" /> {t('lang.label')}
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ToggleGroup type="single" value={i18n.language} onValueChange={v => v && applyLang(v)}>
              <ToggleGroupItem value="zh" className="text-sm">中文</ToggleGroupItem>
              <ToggleGroupItem value="en" className="text-sm">English</ToggleGroupItem>
            </ToggleGroup>
          </CardContent>
        </Card>

        {/* Provider */}
        <Card>
          <CardHeader>
            <CardTitle className="text-sm flex items-center gap-2">
              <Cpu size={16} className="text-primary" /> {t('settings.provider')}
            </CardTitle>
          </CardHeader>
          <CardContent>
            <Select value={app.provider} onValueChange={v => updateApp({ provider: v })}>
              <SelectTrigger className="w-full">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {['claude', 'deepseek', 'openai', 'ollama'].map(p => (
                  <SelectItem key={p} value={p}>{p}</SelectItem>
                ))}
              </SelectContent>
            </Select>
            <p className="mt-2 text-xs text-muted-foreground">
              Model: {app.defaultModel} · Thinking: {app.thinkingLevel}
            </p>
          </CardContent>
        </Card>

        {/* Budget */}
        <Card>
          <CardHeader>
            <CardTitle className="text-sm flex items-center gap-2">
              <DollarSign size={16} className="text-primary" /> 预算
            </CardTitle>
          </CardHeader>
          <CardContent className="flex items-center gap-4">
            <Input type="number" value={app.costBudget}
              onChange={e => updateApp({ costBudget: +e.target.value })}
              className="w-24" />
            <span className="text-sm text-muted-foreground">USD / 月</span>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
